### ISSUE TITLE
href tags on gallery.html

### ISSUE THREAD

**Issue by Stew-McD** [ISIE-2023-CreativeAbstractCompetition/ISIE-2023-CreativeAbstractCompetition.github.io#1]
they go to the center of the section and not to the top, cutting off the section title :( 
plz help soroush

**Comment by sorsaffari** [comment]
@Stew-McD I'm not sure what you mean man? could you share a screenshot of the problem and highlight how you'd like it to be different?

**Comment by Stew-McD** [comment]
[hrefs_EDIT.webm](https://github.com/ISIE-2023-CreativeAbstractCompetition/ISIE-2023-CreativeAbstractCompetition.github.io/assets/81536352/7717ad60-ece2-4cef-8f0d-524611aeeaeb)

this should show it. I tried changing the location of the tag, but it didn't change
